name: 'summaraizer'
description: 'Summaraizer summarizes your GitHub issues and pull requests discussions'
inputs:
  provider:
    description: 'The AI provider to use. Default is openai.'
    required: false
    default: 'ollama'
  provider-args:
    description: 'Arguments (or flags) that will be passed to the provider.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
