name: 'summaraizer'
description: 'Summaraizer summarizes your GitHub issues and pull requests discussions'
inputs:
  gh-token:
    description: 'The GitHub token that read and write access to your repository.'
    required: false
    default: ${{ github.token }}
  provider:
    description: 'The AI provider to use. Default is openai.'
    required: false
    default: 'ollama'
  provider-args:
    description: 'Arguments (or flags) that will be passed to the provider.'
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
